DO
$$
    BEGIN
        IF NOT EXISTS (SELECT
                       FROM pg_database
                       WHERE datname = 'bank_db') THEN
            CREATE DATABASE bank_db;
        END IF;
    END
$$;

\connect bank_db

create table if not exists users
(
    id         int primary key generated by default as identity,
    email      text,
    password   text,
    first_name text,
    last_name  text,
    patronymic text
);

create table if not exists cards
(
    id          int primary key generated by default as identity,
    number      text,
    cvc         text,
    user_id     int references users (id),
    expiry_date text,
    status      text,
    balance     decimal
);

create table if not exists roles
(
    id   int primary key generated by default as identity,
    name text
);

create table if not exists users_and_roles
(
    user_id int references users (id),
    role_id int references roles (id),
    primary key (user_id, role_id)
);






